/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CircleSpinLoader: typeof import('./../../views/components/loaders/CircleSpinLoader.vue')['default']
    Discord: typeof import('./../../views/components/icons/Discord.vue')['default']
    Dropzone: typeof import('./../../views/components/Dropzone.vue')['default']
    Github: typeof import('./../../views/components/icons/Github.vue')['default']
    InputPassword: typeof import('./../../views/components/inputs/InputPassword.vue')['default']
    InputText: typeof import('./../../views/components/inputs/InputText.vue')['default']
    Instagram: typeof import('./../../views/components/icons/Instagram.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    Logo: typeof import('./../../views/components/Logo.vue')['default']
    LogoTeam: typeof import('./../../views/components/LogoTeam.vue')['default']
    SubmitButton: typeof import('./../../views/components/buttons/SubmitButton.vue')['default']
    UserDropdown: typeof import('./../../views/components/UserDropdown.vue')['default']
    ValidationAlert: typeof import('./../../views/components/alerts/ValidationAlert.vue')['default']
  }
}
