name: 'E2E Testování - Laravel Dusk'

on:
  workflow_dispatch:

jobs:
  install-linux:
    name: Instalace & sestavení aplikace na linuxu
    runs-on: ubuntu-latest
    steps:
      - name: Stahování kódu ze repository
        uses: actions/checkout@v3.3.0
        
      - name: Instalace PHP & composeru with JIT
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: phpunit,phpcs,composer,xdebug
          ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M
          extension: opcache,bcmath,ctype,curl,dom,fileinfo,json,mbstring,openssl,pcre,pdo_mysql,tokenizer,xml
                
      - name: Získaní adresy composer cache
        id: composer-cache-path
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        
      - name: Caching composeru
        uses: actions/cache@v3
        id: composer-cache
        with:
          path: ${{ steps.composer-cache-path.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
          
      - name: Instalace composer vendoru
        if: steps.composer-cache.outputs.cache hit != 'true'
        run: composer install --prefer-dist --dev --no-progress
