name: 'E2E Testování - Laravel Dusk'

on:
  workflow_dispatch:

jobs:
  install-linux:
    name: Instalace & sestavení aplikace na linuxu
    runs-on: ubuntu-latest
    steps:
      - name: Stahování kódu ze repository
        uses: actions/checkout@v3.3.0
        
      - name: Instalace PHP & composeru with JIT
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: phpunit,phpcs,composer,xdebug
          ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M
          extensions: opcache,bcmath,ctype,curl,dom,fileinfo,json,mbstring,openssl,pcre,pdo_mysql,tokenizer,xml
                
      - name: Získaní adresy composer cache
        id: composer-cache-path
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        
      - name: Caching composeru
        uses: actions/cache@v3
        id: composer-cache
        with:
          path: ${{ steps.composer-cache-path.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
          
      - name: Instalace composer vendoru
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --dev --no-progress
        
      - name: Instalace NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19
          
      - name: Získání adresy nodejs cache
        id: node-cache-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        
      - name: Caching NodeJS
        uses: actions/cache@v3
        id: node-cache
        with:
          path: ${{ steps.node-cache-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-
      
      - name: Instalace node_modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install
        
      - name: Sestavení aplikace MW UI
        run: yarn build
        
      - name: Upload sestaveného UI pro ostatní úkony
        uses: actions/upload-artifact@v3.1.2
        with:
          name: MWUI
          path: public/build
