name: 'E2E Testování - Laravel Dusk'

on:
  workflow_dispatch:

jobs:
  install-linux:
    name: Instalace & sestavení aplikace na linuxu
    runs-on: ubuntu-latest
    steps:
      - name: Stahování kódu ze repository
        uses: actions/checkout@v3.3.0
        
      - name: Instalace PHP & composeru with JIT
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: phpunit,phpcs,composer,xdebug
          ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M
          extension: opcache,bcmath,ctype,curl,dom,fileinfo,json,mbstring,openssl,pcre,pdo_mysql,tokenizer,xml
