name: "MW UI V3 - BACKEND & FRONTEND"

on:
  pull_request:
    types: [labeled, synchronize, reopened, closed, opened ]
  workflow_dispatch:
  
jobs:
  backend:
    name: CI - BACKEND
    if: ${{ contains(github.event.pull_request.labels.*.name, 'backend') || contains(github.event.name, 'closed') || contains(github.event.pull_request.labels.*.name, 'full-ci') }}
    uses: ./.github/workflows/BACKEND.yaml
  frontend:
    name: CI - FRONTEND
    if: ${{ contains(github.event.pull_request.labels.*.name, 'frontend') || contains(github.event.name, 'closed') || contains(github.event.pull_request.labels.*.name, 'full-ci') }}
    uses: ./.github/workflows/E2E.yaml
  automatic-deployment:
    name: Automatické nasazení
    environment: CI
    if: ${{ contains(github.event.pull_request.labels.*.name, 'autodeploy') || contains(github.event.name, 'closed') || contains(github.event.pull_request.labels.*.name, 'full-ci') }}
    runs-on: ubuntu-latest
    steps:
      - name: Poslat informaci o nasazení aplikace
        uses: Glennmen/ploi-deploy-action@v1.2.0
        with:
          webhook_url: ${{ secrets.PLOI_WEBHOOK }}
